[theme]
primaryColor = "#007ACC"             # Bright blue accent color
backgroundColor = "#FFFFFF"          # White background
secondaryBackgroundColor = "#F0F2F6" # Light gray for sidebar/widgets
textColor = "#000000"                # Black text
font = "sans serif"